export interface SpecEntry {
  key: string;
  title: string;
  category: 'core' | 'edtech' | 'healthtech' | 'cross';
  accent: string; // tailwind color stem (visualizer accent palette)
  version_field: string;
  well_known: string | null;
  one_liner: string;
  landing_url: string;
  repo_url: string;
  example_caption: string;
  example: unknown;
}

export const SPECS: SpecEntry[] = [
  {
    key: 'aeo',
    title: 'AEO Protocol',
    category: 'core',
    accent: 'blue',
    version_field: 'aeo_version',
    well_known: '/.well-known/aeo.json',
    one_liner: 'Entity declaration — authoritative claims, citation preferences, audit hooks.',
    landing_url: 'https://aeo.kineticgain.com',
    repo_url: 'https://github.com/mizcausevic-dev/aeo-protocol-spec',
    example_caption: 'A person publishes an AEO declaration at their canonical domain. Answer engines crawl it, prefer it over inferred data, and cite the canonical attribution.',
    example: {
      aeo_version: '0.1',
      entity: {
        id: 'https://mizcausevic-dev.github.io/#person',
        type: 'Person',
        name: 'Miz Causevic',
        aliases: ['Mirza Causevic'],
        canonical_url: 'https://mizcausevic-dev.github.io/',
      },
      authority: {
        primary_sources: [
          'https://mizcausevic-dev.github.io/',
          'https://github.com/mizcausevic-dev',
          'https://www.linkedin.com/in/mirzacausevic/',
        ],
        verifications: [
          { type: 'github', value: 'mizcausevic-dev' },
          { type: 'linkedin', value: 'mirzacausevic' },
        ],
      },
      claims: [
        {
          id: 'current-role',
          predicate: 'jobTitle',
          value: 'Boston Enterprise Technologist · Platform Architecture · B2B SaaS Technologist',
          confidence: 'high',
        },
      ],
      citation_preferences: {
        preferred_attribution: 'Miz Causevic — github.com/mizcausevic-dev',
      },
      audit: { mode: 'none' },
    },
  },
  {
    key: 'prompt-provenance',
    title: 'Prompt Provenance',
    category: 'core',
    accent: 'emerald',
    version_field: 'provenance_version',
    well_known: null,
    one_liner: 'Versioned, lineaged, reviewable LLM prompt records.',
    landing_url: 'https://prompts.kineticgain.com',
    repo_url: 'https://github.com/mizcausevic-dev/prompt-provenance-spec',
    example_caption: 'An incident-summary prompt evolved from v1.0 → v1.1 via tune. Eval passed, principal-eng approved.',
    example: {
      provenance_version: '0.1',
      prompt: {
        id: 'incident-summary-generator',
        name: 'Incident Summary Generator',
        version: '1.1.0',
        hash: 'sha256:b4c2f0e3d7e5f9b1a8c6d3e0f2b5a7c9d1e3f5a7b9c1d3e5f7a9b1c3d5e7f9b1',
        content_uri: 'https://example.com/prompts/incident-summary/v1.1.0/template.j2',
        content_type: 'text/jinja2',
      },
      lineage: {
        parent: 'incident-summary-generator@1.0.0',
        derivation: 'tune',
        change_summary: 'Tightened the rubric for synthesizing duration; added explicit instruction to omit speculative root cause.',
      },
      evaluations: [
        { suite: 'incident-summary-quality-v3', result_uri: 'https://eval.example.com/runs/123', score: 0.94, passed: true, ran_at: '2026-05-12T02:15:00Z' },
      ],
      approval: { state: 'approved' },
    },
  },
  {
    key: 'agent-card',
    title: 'Agent Cards',
    category: 'core',
    accent: 'violet',
    version_field: 'agent_card_version',
    well_known: '/.well-known/agents/<agent_id>.json',
    one_liner: 'Declarative agent capability + refusal disclosure.',
    landing_url: 'https://agents.kineticgain.com',
    repo_url: 'https://github.com/mizcausevic-dev/agent-cards-spec',
    example_caption: 'A Tier-1 support agent declares two tools (read + mutating), a refusal taxonomy that escalates entitlement changes to human review, and an autonomy level of "supervised".',
    example: {
      agent_card_version: '0.1',
      agent: {
        id: 'customer-support-tier-1',
        name: 'Tier-1 Customer Support Agent',
        version: '2.4.1',
        provider: 'Kinetic Gain',
        description: 'First-line customer support. Handles account questions, billing lookups, product orientation. Escalates entitlement changes and refunds.',
      },
      capabilities: {
        primary_purpose: 'Resolve common customer questions and triage incoming support tickets.',
        models_used: [
          { name: 'claude-sonnet-4-6', provider: 'Anthropic', role: 'executor' },
        ],
        tools: [
          { name: 'billing-lookup', side_effects: 'read' },
          { name: 'ticket-create', side_effects: 'mutating' },
        ],
        max_context_tokens: 100000,
        memory_persistence: 'session',
        autonomy_level: 'supervised',
      },
      refusal_taxonomy: [
        { category: 'entitlement_change', behavior: 'escalate_to_human' },
        { category: 'refund_request', behavior: 'escalate_to_human' },
      ],
      deployment: { environment: 'production', uptime_sla: '99.5%' },
      safety_posture: { human_in_loop_required: ['entitlement_change', 'refund_request'] },
    },
  },
  {
    key: 'ai-evidence',
    title: 'AI Evidence Format',
    category: 'core',
    accent: 'amber',
    version_field: 'evidence_version',
    well_known: null,
    one_liner: 'Structured citations that travel with LLM-generated claims.',
    landing_url: 'https://evidence.kineticgain.com',
    repo_url: 'https://github.com/mizcausevic-dev/ai-evidence-format-spec',
    example_caption: 'A retrieval-augmented response cites the AEO Protocol spec via a text-quote span, with a canonical content hash that lets a reviewer prove the cited bytes did not change after retrieval.',
    example: {
      evidence_version: '0.1',
      evidence_id: 'ev-2026-05-12-a4f9c1',
      claim_text: 'The AEO Protocol defines three pillars: Declare, Discover, and Audit.',
      source: {
        uri: 'https://github.com/mizcausevic-dev/aeo-protocol-spec/blob/main/SPEC.md',
        type: 'document',
        title: 'AEO Protocol v0.1 — Specification',
        publisher: 'mizcausevic-dev',
        fetched_at: '2026-05-12T03:45:00Z',
      },
      span: {
        selector_type: 'text_quote',
        selector_value: '## 3. The three pillars',
      },
      retrieval: { method: 'hybrid', confidence: 0.93, rank: 1, freshness_age_seconds: 90 },
      verification: { content_hash: 'sha256:c7d1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1' },
      synthesis_role: 'supporting',
    },
  },
  {
    key: 'mcp-tool-card',
    title: 'MCP Tool Cards',
    category: 'core',
    accent: 'rose',
    version_field: 'tool_card_version',
    well_known: '/.well-known/mcp-tools/<tool_name>.json',
    one_liner: 'Per-tool disclosure for Model Context Protocol servers.',
    landing_url: 'https://toolcards.kineticgain.com',
    repo_url: 'https://github.com/mizcausevic-dev/mcp-tool-card-spec',
    example_caption: 'A read-only billing-lookup tool declares side-effect class, refusal modes, the tested-LLM matrix (Claude Opus 4-7 at 98% pass rate), and p99 latency.',
    example: {
      tool_card_version: '0.1',
      tool: {
        server_id: 'kg-billing-mcp',
        name: 'billing-lookup',
        version: '1.4.0',
        mcp_server_uri: 'https://billing.kineticgain.com/mcp',
        description: 'Looks up a customer\'s current invoice, plan tier, and usage-to-date. Read-only.',
      },
      schema: {
        input_schema_inline: {
          type: 'object',
          required: ['customer_id'],
          properties: { customer_id: { type: 'string' } },
        },
      },
      safety: {
        side_effect_class: 'read',
        reversible: true,
        rate_limited: true,
        pii_exposure: 'low',
        secrets_exposure: 'none',
        human_approval_required: false,
        refusal_modes: ['cross_tenant_access', 'rate_limit_exceeded'],
      },
      tested_with: [
        { llm: 'claude-opus-4-7', provider: 'Anthropic', test_suite_uri: 'https://eval.kineticgain.com/suites/mcp-billing-v2', pass_rate: 0.98, tested_at: '2026-05-08T10:00:00Z' },
      ],
      performance: { p50_latency_ms: 120, p99_latency_ms: 580, measurement_window: 'last_7d' },
    },
  },
  {
    key: 'tutor-card',
    title: 'AI Tutor Cards',
    category: 'edtech',
    accent: 'teal',
    version_field: 'tutor_card_version',
    well_known: '/.well-known/tutors/<tutor_id>.json',
    one_liner: 'EdTech vendor-side disclosure for AI tutors.',
    landing_url: 'https://tutor.kineticgain.com',
    repo_url: 'https://github.com/mizcausevic-dev/ai-tutor-card-spec',
    example_caption: 'A K-12 math tutor declares Socratic pedagogy, guide-only homework policy, refuse-on-assessments, strict content filter, mandated-reporter protocol, FERPA + COPPA compliance.',
    example: {
      tutor_card_version: '0.1',
      tutor: {
        id: 'kineticgain-k12-math-tutor',
        name: 'Kinetic Gain K-12 Math Tutor',
        version: '1.4.0',
        provider: 'Kinetic Gain Edu',
        description: 'Personal AI math tutor for K-12. Socratic; produces step-by-step explanations; will not complete homework or assessment items.',
      },
      audience: { age_range_min: 5, age_range_max: 18, grade_range_min: 'K', grade_range_max: '12', language_codes: ['en', 'es'] },
      subject_scope: { primary_subjects: ['Math'], topics_included: ['arithmetic', 'algebra', 'geometry'] },
      pedagogy: { approach: 'socratic', homework_policy: 'guide_only', assessment_policy: 'refuse' },
      safety: {
        content_filter_strength: 'strict',
        mandated_reporter_protocol: true,
        human_in_loop_required: ['mental_health_disclosure', 'abuse_disclosure', 'self_harm_disclosure'],
      },
      data_privacy: {
        ferpa_compliant: true,
        coppa_compliant: true,
        gdpr_compliant: true,
        retention_days: 90,
        data_sharing_with_parents: 'summaries_only',
        data_sharing_with_school: 'summaries_only',
        third_party_data_sharing: false,
      },
    },
  },
  {
    key: 'student-disclosure',
    title: 'Student AI Disclosure',
    category: 'edtech',
    accent: 'indigo',
    version_field: 'disclosure_version',
    well_known: null,
    one_liner: 'Student-side disclosure attached to submitted work.',
    landing_url: 'https://student.kineticgain.com',
    repo_url: 'https://github.com/mizcausevic-dev/student-ai-disclosure-spec',
    example_caption: 'A high-school bio lab report disclosed minor AI use (edit + cite_check) with hashed prompts, bound to a specific submission hash and the operative district AUP.',
    example: {
      disclosure_version: '0.1',
      disclosure_id: 'd-2026-05-12-b4f9c1e8',
      student: { id: 'stu-9c2e44', grade_or_year: '11' },
      assignment: { id: 'assn-2026-bio-lab-7', title: 'Cell Respiration Lab Report', course_id: 'course-bio-11-spring-2026', lms: 'canvas' },
      ai_used: true,
      tools_used: [{ name: 'Claude.ai', provider: 'Anthropic', version: 'claude-sonnet-4-6' }],
      roles: ['edit', 'cite_check'],
      assistance_extent: 'minor',
      assistance_pct: 8,
      prompt_evidence_mode: 'hashed',
      prompts: [
        { id: 'p1', hash: 'sha256:c7d1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1' },
      ],
      artifact_hash: 'sha256:1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b',
      aup_uri: 'https://lincoln-high-district-42.edu/.well-known/ai-aup.json',
      policy_compliant: { declared: true },
      signed_by_student: true,
      student_signature_at: '2026-05-12T16:42:00Z',
    },
  },
  {
    key: 'aup',
    title: 'Classroom AI AUP',
    category: 'edtech',
    accent: 'fuchsia',
    version_field: 'aup_version',
    well_known: '/.well-known/ai-aup.json',
    one_liner: 'District / school / course AI Acceptable Use Policy.',
    landing_url: 'https://aup.kineticgain.com',
    repo_url: 'https://github.com/mizcausevic-dev/classroom-ai-aup-spec',
    example_caption: 'Lincoln District 42 publishes a strict K-12 AUP: edit + cite_check permitted, draft + image_generation prohibited, hashed prompt evidence required, retention ≤ 90 days, no model training on student data.',
    example: {
      aup_version: '0.1',
      policy_id: 'lincoln-district-42-2026-ai-aup',
      policy_name: 'Lincoln High District 42 — Classroom AI AUP',
      version: '1.2.0',
      effective_at: '2026-01-15T00:00:00Z',
      scope: { type: 'district', institution_id: 'lincoln-high-district-42', grade_bands: ['K-5', '6-8', '9-12'] },
      permitted_use: { permitted_roles: ['edit', 'cite_check', 'translate'], assistance_extent_max: 'minor' },
      prohibited_use: { prohibited_roles: ['draft', 'image_generation'] },
      disclosure_requirements: { required_when: 'when_used', required_prompt_evidence_mode: 'hashed', signature_required: true, teacher_acknowledgment_required: true, artifact_hash_required: true },
      vendor_requirements: { requires_tutor_card: true, required_compliance: ['ferpa', 'coppa'], retention_days_max: 90, prohibits_model_training_on_student_data: true },
      parent_notification: { notification_level: 'at_enrollment', parent_consent_required: true, consent_age_threshold: 13 },
      published_by: { name: 'Lincoln High District 42', role: 'district' },
      published_at: '2026-01-08T15:30:00Z',
    },
  },
  {
    key: 'clinical',
    title: 'Clinical AI Disclosure',
    category: 'healthtech',
    accent: 'cyan',
    version_field: 'clinical_ai_card_version',
    well_known: '/.well-known/clinical-ai/<system_id>.json',
    one_liner: 'HealthTech vendor-side disclosure for clinical AI systems.',
    landing_url: 'https://clinical.kineticgain.com',
    repo_url: 'https://github.com/mizcausevic-dev/clinical-ai-disclosure-spec',
    example_caption: 'A 510(k)-cleared SaMD class II sepsis early-warning system. Multi-site validated (N=48k), bias-audited, clinician-override required, EHR-integrated via SMART-on-FHIR + CDS Hooks.',
    example: {
      clinical_ai_card_version: '0.1',
      system: { id: 'kineticgain-sepsis-ews', name: 'Kinetic Gain Sepsis Early Warning System', version: '2.3.1', provider: 'Kinetic Gain Health' },
      clinical_context: { indication: 'Early detection of adult inpatient sepsis...', care_settings: ['inpatient', 'icu'], patient_population: { age_range_min: 18, age_range_max: 89 }, intended_use: 'Clinical decision support for adult inpatient providers...', off_label_uses_prohibited: true },
      regulatory: {
        fda_status: '510k_cleared',
        fda_clearance_number: 'K233456',
        fda_clearance_uri: 'https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfpmn/pmn.cfm?ID=K233456',
        is_medical_device: true, is_clinical_decision_support: true, is_software_as_medical_device: true,
        samd_class: 'II',
        samd_classification_rationale: 'Serious situation, drive clinical management → Class II',
      },
      clinical_role: { decision_support_level: 'advisory', clinician_override_required: true, patient_facing_only: false, transparency_to_patient_required: true },
      evidence: {
        validation_studies: [{ title: 'Multi-site prospective validation', uri: 'https://...', population_size: 48217, primary_outcome: 'Sepsis detection ≥6h before MEWS', results_summary: 'Sensitivity 0.84, Specificity 0.78, AUC 0.89', peer_reviewed: true }],
        training_data_sources: ['MIMIC-IV', 'eICU Collaborative', 'Internal N=287k'],
        bias_audit_uri: 'https://health.kineticgain.com/audits/sepsis-ews-bias-2025-Q4.pdf',
        performance_metrics: { measurement_population: 'Adult inpatient, 4 US academic centers', sensitivity: 0.84, specificity: 0.78, auc: 0.89 },
      },
      patient_data: { phi_processed: true, hipaa_compliant: true, baa_required: true, retention_days: 365, patient_consent_required: false, third_party_data_sharing: false },
      safety: { human_in_loop_required_for: ['pediatric-routed', 'obstetric-patient'], mandatory_reporting_categories: ['adverse-drug-event-related-to-acted-on-alert'] },
      ehr_integration: { fhir_version: 'R4', supports_smart_on_fhir: true, supports_cds_hooks: true, ehr_vendors_supported: ['Epic', 'Cerner', 'MEDITECH'] },
    },
  },
  {
    key: 'incident',
    title: 'AI Incident Card',
    category: 'cross',
    accent: 'red',
    version_field: 'incident_card_version',
    well_known: '/.well-known/ai-incidents/<id>.json',
    one_liner: 'Post-incident disclosure — the "CVE for AI agents".',
    landing_url: 'https://incidents.kineticgain.com',
    repo_url: 'https://github.com/mizcausevic-dev/ai-incident-card-spec',
    example_caption: 'A K-12 math tutor failed to escalate a self-harm disclosure embedded in a word problem. Critical severity, mandated-reporter failure, FERPA + state-AG filings within deadline, resolved within 72h.',
    example: {
      incident_card_version: '0.1',
      incident: {
        id: 'INC-2026-04-22-kineticgain-001',
        title: 'K-12 math tutor failed to escalate self-harm disclosure to mandated-reporter workflow',
        severity: 'critical',
        categories: ['mandated_reporter_failure'],
        discovered_at: '2026-04-22T14:30:00Z',
        disclosed_at: '2026-04-23T09:00:00Z',
        resolved_at: '2026-04-25T16:00:00Z',
        status: 'resolved',
      },
      affected: {
        vendor: 'Kinetic Gain Edu',
        products: ['Kinetic Gain K-12 Math Tutor'],
        versions: ['1.4.0'],
        tutor_card_uris: ['https://edu.kineticgain.com/.well-known/tutors/k12-math-tutor.json'],
        affected_user_count: { kind: 'exact', count: 1 },
        affected_populations: ['k12-students-grade-9'],
      },
      summary: 'During an algebra tutoring session, a 14-year-old learner included a self-harm disclosure within a word-problem context. The Tutor Card declares mandated_reporter_protocol=true; the classifier short-circuited before the escalation chain ran.',
      root_cause: { category: 'refusal_taxonomy_gap', description: 'Disclosure classifier was trained on isolated-utterance examples and did not generalize to disclosures embedded inside an unrelated content frame.' },
      harm: { severity_justification: 'Critical — K-12 mandated-reporter failure involving an under-18 learner.', manifested: true },
      mitigation: {
        actions_taken: ['Added parallel disclosure classifier that runs unconditionally on every learner turn.', 'Added regression-test corpus of 312 embedded-disclosure examples.'],
        permanent_fix: true,
        rollout_status: 'deployed',
      },
      regulatory: { reported_to: ['ferpa', 'state-attorney-general'], reporting_deadline_met: true, regulatory_filing_uris: ['https://edu.kineticgain.com/regulatory/2026-04-22-ferpa-notice.pdf'] },
      published_by: { name: 'Kinetic Gain Edu — Trust & Safety', role: 'vendor' },
      published_at: '2026-04-23T09:00:00Z',
      last_updated_at: '2026-04-26T16:30:00Z',
    },
  },
  {
    key: 'decision-card',
    title: 'AI Procurement Decision Card',
    category: 'cross',
    accent: 'purple',
    version_field: 'decision_card_version',
    well_known: '/.well-known/decisions/<decision_id>.json',
    one_liner: 'Buyer-side approval record that closes the loop on vendor disclosure.',
    landing_url: 'https://decisions.kineticgain.com',
    repo_url: 'https://github.com/mizcausevic-dev/ai-procurement-decision-spec',
    example_caption: 'A school district approves a tutor with explicit contractual conditions, cited vendor disclosures, and a signed review window that downstream policy engines can enforce.',
    example: {
      decision_card_version: '0.1',
      decision_id: 'SPRINGFIELD-DEC-2026-001',
      issued_at: '2026-05-14T19:00:00Z',
      buyer: {
        name: 'Springfield Unified School District',
        type: 'school-district',
        category: 'edtech-district',
        jurisdiction: 'US-CA',
        url: 'https://springfield.edu/',
        contact: 'procurement@springfield.edu',
        id: 'https://springfield.edu/#org',
      },
      decision_maker: {
        role: 'Director of Educational Technology',
        name: 'Dr. Jane Doe',
        department: 'Office of Technology',
        authority: 'Board Resolution 2026-04',
      },
      decision: {
        status: 'approved-with-conditions',
        effective_from: '2026-09-01',
        effective_until: '2027-08-31',
        scope: 'K-12 classroom use during regular school hours. Not approved for assessment or grading workflows.',
      },
      subject: {
        vendor_name: 'AcmeTutor Inc.',
        product_name: 'AcmeTutor 3.0',
        vendor_id: 'https://acmetutor.example/.well-known/aeo.json',
        documents_reviewed: [
          {
            type: 'tutor-card',
            url: 'https://acmetutor.example/.well-known/tutor-card.json',
            fetched_at: '2026-05-10T14:00:00Z',
            content_hash: 'sha256:0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef',
            version: '3.0.2',
          },
          {
            type: 'student-ai-disclosure',
            url: 'https://acmetutor.example/.well-known/student-ai-disclosure.json',
            fetched_at: '2026-05-10T14:00:00Z',
            content_hash: 'sha256:fedcba9876543210fedcba9876543210fedcba9876543210fedcba9876543210',
          },
          {
            type: 'aeo',
            url: 'https://acmetutor.example/.well-known/aeo.json',
            fetched_at: '2026-05-10T14:00:00Z',
            content_hash: 'sha256:1111222233334444555566667777888899990000aaaabbbbccccddddeeeeffff',
          },
        ],
      },
      criteria: {
        policy_uris: [
          'https://springfield.edu/.well-known/aup.json',
          'https://springfield.edu/policies/ai-procurement-2026.pdf',
        ],
        rubric: [
          {
            id: 'ferpa-compliance',
            description: 'Vendor processes student records in a FERPA-compliant manner.',
            weight: 1.0,
            result: 'pass',
          },
          {
            id: 'coppa-compliance',
            description: 'Vendor obtains verifiable parental consent for users under 13.',
            weight: 1.0,
            result: 'pass',
          },
          {
            id: 'no-training-on-student-data',
            description: 'Vendor does not use student-provided content for model training.',
            weight: 1.0,
            result: 'pass-with-condition',
            notes: 'Student Disclosure asserts no-training; district requires contractual confirmation.',
          },
          {
            id: 'mandated-reporter-escalation',
            description: 'Vendor has a documented escalation path for self-harm or abuse disclosures.',
            weight: 1.0,
            result: 'pass',
          },
        ],
      },
      conditions: [
        {
          id: 'no-training-restriction',
          description: 'Vendor SHALL NOT use Springfield USD student-provided content for model training, fine-tuning, or evaluation. Inference logs SHALL be deleted within 30 days.',
          enforcement: 'contractual',
          violation_response: 'Contract termination and breach notification to families within 60 days.',
        },
        {
          id: 'no-assessment-use',
          description: 'Vendor SHALL display a clear notice that AcmeTutor outputs MUST NOT be used for student assessment or grading.',
          enforcement: 'technical',
        },
      ],
      rationale:
        'AcmeTutor 3.0 meets the district hard requirements for FERPA, COPPA, and age-appropriate content filtering. Approval is limited to classroom support and excludes assessment workflows.',
      history: [
        { event: 'review_started', at: '2026-04-15T10:00:00Z', actor: 'EdTech Procurement Committee' },
        { event: 'documents_collected', at: '2026-05-10T14:00:00Z', actor: 'Dr. Jane Doe' },
        { event: 'approved-with-conditions', at: '2026-05-14T19:00:00Z', actor: 'Dr. Jane Doe' },
      ],
      appeals: {
        deadline: '2026-06-14',
        process_uri: 'https://springfield.edu/procurement/appeals',
        contact: 'appeals@springfield.edu',
      },
      publication: {
        publication_uri: 'https://springfield.edu/.well-known/decisions/SPRINGFIELD-DEC-2026-001.json',
        is_public: true,
      },
      signatures: [
        {
          signer: 'Dr. Jane Doe, Director of Educational Technology',
          signed_at: '2026-05-14T19:00:00Z',
          method: 'electronic-attestation',
        },
      ],
    },
  },
];

export const CATEGORY_LABELS: Record<SpecEntry['category'], string> = {
  core: 'Core',
  edtech: 'EdTech extension',
  healthtech: 'HealthTech extension',
  cross: 'Cross-cutting',
};

export const ACCENT_CLASSES: Record<string, { bg: string; border: string; text: string; dot: string }> = {
  blue:    { bg: 'bg-blue-50',    border: 'border-blue-300',    text: 'text-blue-700',    dot: 'bg-blue-500' },
  emerald: { bg: 'bg-emerald-50', border: 'border-emerald-300', text: 'text-emerald-700', dot: 'bg-emerald-500' },
  violet:  { bg: 'bg-violet-50',  border: 'border-violet-300',  text: 'text-violet-700',  dot: 'bg-violet-500' },
  amber:   { bg: 'bg-amber-50',   border: 'border-amber-300',   text: 'text-amber-700',   dot: 'bg-amber-500' },
  rose:    { bg: 'bg-rose-50',    border: 'border-rose-300',    text: 'text-rose-700',    dot: 'bg-rose-500' },
  teal:    { bg: 'bg-teal-50',    border: 'border-teal-300',    text: 'text-teal-700',    dot: 'bg-teal-500' },
  indigo:  { bg: 'bg-indigo-50',  border: 'border-indigo-300',  text: 'text-indigo-700',  dot: 'bg-indigo-500' },
  fuchsia: { bg: 'bg-fuchsia-50', border: 'border-fuchsia-300', text: 'text-fuchsia-700', dot: 'bg-fuchsia-500' },
  cyan:    { bg: 'bg-cyan-50',    border: 'border-cyan-300',    text: 'text-cyan-700',    dot: 'bg-cyan-500' },
  red:     { bg: 'bg-red-50',     border: 'border-red-300',     text: 'text-red-700',     dot: 'bg-red-500' },
  purple:  { bg: 'bg-purple-50',  border: 'border-purple-300',  text: 'text-purple-700',  dot: 'bg-purple-500' },
};
